apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: subscription-function3
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: cj-2
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: function3b
