apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: cronjob-source-to-service
spec:
  schedule: "* * * * *"
  data: '{"message": "Hello from cronjob-source-to-service"}'
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: event-display
