apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: event-process
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/csantanapr/process-event-change
